# Generated by Django 3.1.3 on 2020-11-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telegram_id',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.TextField(null=True),
        ),
    ]
